import { agentRegistry } from "@/lib/agents/registry";
import { DEFAULT_MOCK_TEAM_ID } from "@/lib/data/mock-team";
import { getAgentById, getAgentTaskById } from "@/lib/services/agent-tasks";
import { routeTaskToAgent } from "@/lib/services/agent-router";
import type { AgentTaskRecord } from "@/lib/types/agents";
import type {
  AgentExecutionMode,
  AgentExecutionPackage,
  AgentExecutionResult,
  AgentExecutionStatus,
  RecordExecutionResultInput,
} from "@/lib/types/agent-execution";

const activeExecutionStatuses: AgentExecutionStatus[] = ["draft", "packaged", "dispatched", "in_progress", "needs_review"];

const executionPackagesStore: AgentExecutionPackage[] = [];
const executionResultsStore: AgentExecutionResult[] = [];

function nowIso() {
  return new Date().toISOString();
}

function createExecutionPackageId() {
  return `execution_pkg_${crypto.randomUUID().slice(0, 8)}`;
}

function createExecutionResultId() {
  return `execution_result_${crypto.randomUUID().slice(0, 8)}`;
}

function formatTaskTypeLabel(value: string) {
  return value.replaceAll("_", " ");
}

function formatSchemaText(task: AgentTaskRecord) {
  if (!task.outputSchema) {
    return "No structured schema is registered for this task. Return a concise structured response and call out missing fields.";
  }

  const properties = Object.entries(task.outputSchema.properties).map(([key, field]) => {
    const enumText = field.enum ? ` Allowed values: ${field.enum.join(", ")}.` : "";
    const itemsText = field.itemsType ? ` Array items: ${field.itemsType}.` : "";
    return `- ${key}: ${field.type}. ${field.description}${itemsText}${enumText}`;
  });

  return [
    `Expected output type: ${task.outputSchema.type}.`,
    `Required fields: ${task.outputSchema.required.join(", ") || "none"}.`,
    "Schema fields:",
    ...properties,
  ].join("\n");
}

function getTaskRequest(task: AgentTaskRecord) {
  const prompt = typeof task.input.prompt === "string" ? task.input.prompt.trim() : "";

  if (prompt.length > 0) {
    return prompt;
  }

  return `Complete the ${formatTaskTypeLabel(task.taskType)} contract for task ${task.id}.`;
}

function getExecutionMode(task: AgentTaskRecord): AgentExecutionMode {
  const routing = routeTaskToAgent({
    request: getTaskRequest(task),
    taskType: task.taskType,
    priority: task.priority,
    context: task.input,
  });

  return routing.supportingAgentIds.length > 0 ? "assisted" : "manual";
}

function buildContextPayload(task: AgentTaskRecord) {
  const routing = routeTaskToAgent({
    request: getTaskRequest(task),
    taskType: task.taskType,
    priority: task.priority,
    context: task.input,
  });
  const assignedAgent = getAgentById(task.agentId);

  return {
    bridgeMode: "manual_contract_only",
    liveExecutionAvailable: false,
    manualHandoffRequired: true,
    task: {
      id: task.id,
      agentId: task.agentId,
      agentName: task.agentName,
      taskType: task.taskType,
      priority: task.priority,
      status: task.status,
      input: task.input,
      nextStep: task.nextStep,
    },
    assignedAgent: assignedAgent
      ? {
          id: assignedAgent.id,
          name: assignedAgent.name,
          role: assignedAgent.role,
          description: assignedAgent.description,
          capabilities: assignedAgent.capabilities,
        }
      : null,
    routing: {
      primaryAgentId: routing.primaryAgentId,
      supportingAgentIds: routing.supportingAgentIds,
      executionOrder: routing.executionOrder,
      requiredInputs: routing.requiredInputs,
      expectedOutputs: routing.expectedOutputs,
      handoffPlan: routing.handoffPlan,
    },
    handoffTargets: assignedAgent?.handoffTargets ?? [],
  };
}

export function buildAgentInstructionPrompt(task: AgentTaskRecord) {
  const agent = getAgentById(task.agentId) ?? agentRegistry.find((entry) => entry.id === task.agentId) ?? null;
  const routing = routeTaskToAgent({
    request: getTaskRequest(task),
    taskType: task.taskType,
    priority: task.priority,
    context: task.input,
  });
  const handoffTargets = (agent?.handoffTargets ?? []).map(
    (targetId) => agentRegistry.find((entry) => entry.id === targetId)?.name ?? targetId,
  );

  return [
    `Execution package for ${task.agentName}.`,
    "",
    "Important operating note:",
    "This package was generated by runners-circle-agent-os for manual or assisted execution only.",
    "There is currently no direct ChatGPT Agent API bridge in this app, so do not assume automatic dispatch occurred.",
    "",
    `Assigned agent: ${agent?.name ?? task.agentName}`,
    `Role: ${agent?.role ?? "Unknown role"}`,
    `Task id: ${task.id}`,
    `Task type: ${formatTaskTypeLabel(task.taskType)}`,
    `Priority: ${task.priority}`,
    "",
    "Task request:",
    getTaskRequest(task),
    "",
    "Task input payload:",
    JSON.stringify(task.input, null, 2),
    "",
    "Expected output contract:",
    formatSchemaText(task),
    "",
    "Routing context:",
    `- Primary lane: ${routing.primaryAgentId}`,
    `- Supporting lanes: ${routing.supportingAgentIds.join(", ") || "none"}`,
    `- Expected outputs: ${routing.expectedOutputs.join(", ")}`,
    "",
    "Handoff targets after completion:",
    handoffTargets.length > 0 ? `- ${handoffTargets.join("\n- ")}` : "- No handoff targets registered.",
    "",
    "Response instructions:",
    "- Return structured output that matches the expected output contract.",
    "- If an input is missing, explicitly call it out instead of inventing it.",
    "- Keep the result focused on the assigned task contract.",
    "- Include concise notes that help the next downstream agent continue the work.",
  ].join("\n");
}

export function getExecutionPackages() {
  return [...executionPackagesStore].sort((left, right) => Date.parse(right.updatedAt) - Date.parse(left.updatedAt));
}

export function getExecutionPackage(packageId: string) {
  return executionPackagesStore.find((executionPackage) => executionPackage.id === packageId) ?? null;
}

export function getLatestExecutionPackageForTask(taskId: string) {
  return getExecutionPackages().find((executionPackage) => executionPackage.taskId === taskId) ?? null;
}

export function createExecutionPackage(taskId: string) {
  const task = getAgentTaskById(taskId);

  if (!task) {
    return null;
  }

  const latestPackage = getLatestExecutionPackageForTask(taskId);

  if (latestPackage && activeExecutionStatuses.includes(latestPackage.status)) {
    return latestPackage;
  }

  const agent = getAgentById(task.agentId);
  const timestamp = nowIso();
  const executionPackage: AgentExecutionPackage = {
    id: createExecutionPackageId(),
    taskId: task.id,
    agentId: task.agentId,
    agentName: task.agentName,
    teamId: task.teamId ?? DEFAULT_MOCK_TEAM_ID,
    executionMode: getExecutionMode(task),
    status: "packaged",
    reviewStatus: null,
    assignedReviewerId: null,
    taskType: task.taskType,
    priority: task.priority,
    instructionPrompt: buildAgentInstructionPrompt(task),
    contextPayload: buildContextPayload(task),
    expectedOutputSchema: task.outputSchema ?? agent?.outputSchema[task.taskType] ?? null,
    handoffTargets: agent?.handoffTargets ?? [],
    createdAt: timestamp,
    updatedAt: timestamp,
  };

  executionPackagesStore.unshift(executionPackage);

  // TODO: Persist execution packages when the live database bridge is added.
  // TODO: Replace manual packaging with direct ChatGPT Agent dispatch when a supported API exists.

  return executionPackage;
}

export function updateExecutionPackageStatus(packageId: string, status: AgentExecutionStatus) {
  const executionPackage = executionPackagesStore.find((entry) => entry.id === packageId);

  if (!executionPackage) {
    return null;
  }

  executionPackage.status = status;
  executionPackage.updatedAt = nowIso();

  // TODO: Sync package status changes to persistence and live execution telemetry later.

  return executionPackage;
}

export function recordExecutionResult(input: RecordExecutionResultInput) {
  const executionPackage = getExecutionPackage(input.packageId);

  if (!executionPackage) {
    return null;
  }

  const result: AgentExecutionResult = {
    id: createExecutionResultId(),
    packageId: input.packageId,
    status: input.status,
    output: input.output,
    reviewNotes: input.reviewNotes,
    nextRecommendedAgentId: input.nextRecommendedAgentId ?? null,
    createdAt: nowIso(),
  };

  executionResultsStore.unshift(result);
  updateExecutionPackageStatus(input.packageId, input.status);

  // TODO: Persist execution results and connect them to downstream ChatGPT Agent telemetry when available.

  return result;
}

export function getExecutionResults(packageId: string) {
  return executionResultsStore
    .filter((result) => result.packageId === packageId)
    .sort((left, right) => Date.parse(right.createdAt) - Date.parse(left.createdAt));
}

export function getLatestExecutionResult(packageId: string) {
  return getExecutionResults(packageId)[0] ?? null;
}
